language: ruby
cache:
  directories:
    - vendor/bundle
rvm:
  - 1.9.3
  - 2.1.5
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.x.gemfile
  - gemfiles/sinatra1.x.gemfile
notifications:
  email: false
