before_install: gem install bundler -v 1.17.3
cache: bundler
gemfile:
  - gemfiles/rails4.2.x.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails5.x.gemfile
  - gemfiles/sinatra1.x.gemfile
  - gemfiles/sinatra2.x.gemfile
language: ruby
matrix:
  fast_finish: true
notifications:
  email: false
rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2
sudo: false
