---

before_install:
  - "gem install bundler -v 2.1.3"
branches:
  only:
    - "master"
    - '/^v\d+\.\d+\.\d+/'
cache:
  bundler: true
dist: "bionic"
install:
  - "bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
jobs:
  fail_fast: true
  include:
    - rvm: "2.7.1"
      stage: "Test"

    - gemfile: "gemfiles/rails_latest.gemfile"
      rvm: "2.7.1"
      stage: "Latest Rails Release"
    - gemfile: "gemfiles/rails_latest.gemfile"
      rvm: "2.6.6"
    - gemfile: "gemfiles/rails_latest.gemfile"
      rvm: "2.5.8"

    - gemfile: "gemfiles/rails6.0.gemfile"
      rvm: "2.7.1"
      stage: "Additinal Rails Tests"
    - gemfile: "gemfiles/rails6.0.gemfile"
      rvm: "2.6.6"
    - gemfile: "gemfiles/rails6.0.gemfile"
      rvm: "2.5.8"
    - gemfile: "gemfiles/rails5.2.gemfile"
      rvm: "2.7.1"
    - gemfile: "gemfiles/rails5.2.gemfile"
      rvm: "2.6.6"
    - gemfile: "gemfiles/rails5.2.gemfile"
      rvm: "2.5.8"

    - gemfile: "gemfiles/sinatra2.x.gemfile"
      rvm: "2.7.1"
      stage: "Sinatra 2.x Release"
    - gemfile: "gemfiles/sinatra2.x.gemfile"
      rvm: "2.6.6"
    - gemfile: "gemfiles/sinatra2.x.gemfile"
      rvm: "2.5.8"
language: "ruby"
notifications:
  email: false
script:
  - "bundle exec rubocop -fs"
  - "bundle exec rake"
