language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.2.0
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.x.gemfile
  - gemfiles/sinatra1.x.gemfile
notifications:
  email: false
