---

before_install:
  - "gem install bundler -v 2.1.3"
install:
  - "bundle config set deployment 'true'"
  - "bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
branches:
  only:
    - "master"
    - '/^v\d+\.\d+\.\d+/'
cache:
  bundler: true
dist: "xenial"
jobs:
  fail_fast: true
  include:
    - rvm: "2.7.0"
      stage: "Test"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.7.0"
      stage: "Latest Rails Release"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.6.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.5.7"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails6.0.gemfile"
      rvm: "2.7.0"
      stage: "Additinal Rails Tests"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails6.0.gemfile"
      rvm: "2.6.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails6.0.gemfile"
      rvm: "2.5.7"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.7.0"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.6.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.5.7"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.4.9"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.7.0"
      stage: "Sinatra 2.x Release"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.6.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.5.7"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.4.9"
language: "ruby"
notifications:
  email: false
script:
  - "bundle exec rubocop -fs"
  - "bundle exec rake"
