---

before_install:
  - "gem install bundler -v 2.0.2"
branches:
  only:
    - "master"
    - '/^v\d+\.\d+\.\d+/'
cache:
  bundler: true
dist: "xenial"
jobs:
  fail_fast: true
  include:
    - rvm: "2.6.3"
      script:
        - "bundle exec rubocop -fs"
        - "bundle exec rake"
      stage: "Test"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.6.3"
      stage: "Latest Rails Release"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.5.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails_latest.gemfile"
      rvm: "2.4.6"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.6.3"
      stage: "Additinal Rails Tests"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.5.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.2.gemfile"
      rvm: "2.4.6"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.1.gemfile"
      rvm: "2.6.3"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.1.gemfile"
      rvm: "2.5.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.1.gemfile"
      rvm: "2.4.6"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.0.gemfile"
      rvm: "2.6.3"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.0.gemfile"
      rvm: "2.5.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/rails5.0.gemfile"
      rvm: "2.4.6"

    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.6.3"
      stage: "Sinatra 2.x Release"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.5.5"
    - env: "BUNDLE_GEMFILE=$PWD/gemfiles/sinatra2.x.gemfile"
      rvm: "2.4.6"
language: "ruby"
notifications:
  email: false
sudo: false
