language: ruby
cache:
  directories:
  - vendor/bundle
rvm:
  - 1.9.3
  - 2.2.0
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/sinatra1.x.gemfile
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "gxEt3SeVn1kup6PfB6hiQu6eWsefmMEdd8U1qPSS6vlRjsM7Xy2IrXdz9gdl\n0nrrRgESvOxT3sqMh4/opH6M1kbtCyl3M0yvjF2QUtjWQ+4BStJGhNyXlDTp\nNAas19fuEUPBNxNqoy7aTVBiFpQRs0NisEZTS3+N3eA2tz757Qk="
