language: ruby
cache:
  directories:
  - vendor/bundle
rvm:
  - 1.9.3
  - 2.2.0
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/sinatra1.x.gemfile
notifications:
  email: false
